name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file docker/ubuntu-build/Dockerfile --tag svxlink:latest
    #- name: Run build
    #  run: docker run -v `pwd`/artefacts:/usr/local/bin -v `pwd`/config:/usr/local/etc mmdvm:latest
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: artifact-ubuntu-latest.tar.gz
    #    path: |
    #      artefacts/
